version: '3'
services: 
    mongo:
        image: 'mongo:latest'
    application:
        build:
            dockerfile: Dockerfile
            context: ./bluestack
        environment: 
            - MONGO_HOST=mongo
            - MONGO_PORT=27017